PROJECT_DONE = 1
PROJECT_IN_PROCESS = 2
PROJECT_FROZEN = 3

PROJECT_STATUSES = (
    (PROJECT_DONE, 'DONE'),
    (PROJECT_IN_PROCESS, 'IN_PROCESS'),
    (PROJECT_FROZEN, 'FROZEN')
)

TASKS_DONE = 1
TASKS_IN_PROCESS = 2
TASKS_FROZEN = 3

BLOCK_STATUSES = (
    (TASKS_DONE, 'DONE'),
    (TASKS_IN_PROCESS, 'IN_PROCESS'),
    (TASKS_FROZEN, 'FROZEN')
)